$primary_paletteKeyColor = 467baf
$secondary_paletteKeyColor = 996e4d
$tertiary_paletteKeyColor = 677f48
$neutral_paletteKeyColor = 857370
$neutral_variant_paletteKeyColor = 8c716d
$background = 1c110f
$onBackground = f5ddda
$surface = 1c110f
$surfaceDim = 1c110f
$surfaceBright = 443634
$surfaceContainerLowest = 160b0a
$surfaceContainerLow = 251917
$surfaceContainer = 291d1b
$surfaceContainerHigh = 342725
$surfaceContainerHighest = 40312f
$onSurface = f5ddda
$surfaceVariant = 58413e
$onSurfaceVariant = dfbfba
$inverseSurface = f5ddda
$inverseOnSurface = 3b2d2b
$outline = a78a86
$outlineVariant = 58413e
$shadow = 000000
$scrim = 000000
$surfaceTint = 9bcaff
$primary = 9bcaff
$onPrimary = 003256
$primaryContainer = 00497a
$onPrimaryContainer = d0e4ff
$inversePrimary = 286294
$secondary = f0bc96
$onSecondary = 48290d
$secondaryContainer = 654123
$onSecondaryContainer = ffdcc4
$tertiary = b4d091
$onTertiary = 223607
$tertiaryContainer = 80995f
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = d0e4ff
$primaryFixedDim = 9bcaff
$onPrimaryFixed = 001d35
$onPrimaryFixedVariant = 00497a
$secondaryFixed = ffdcc4
$secondaryFixedDim = f0bc96
$onSecondaryFixed = 2f1400
$onSecondaryFixedVariant = 623f21
$tertiaryFixed = d0ecab
$tertiaryFixedDim = b4d091
$onTertiaryFixed = 102000
$onTertiaryFixedVariant = 374d1c
$term0 = 343434
$term1 = 8383ff
$term2 = 44def5
$term3 = 75fcdd
$term4 = 85afd0
$term5 = 92a8ef
$term6 = 8ed2f5
$term7 = ccdcd6
$term8 = ac9fa9
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = aac4d7
$term13 = adbdf8
$term14 = ace3ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = d1dcff
$mauve = 9fc1ff
$red = 9bb0ff
$maroon = b1bcf1
$peach = e0c2f9
$yellow = d0f9f4
$green = b9e6ff
$teal = c1e4ff
$sky = bcdfff
$sapphire = 96ccff
$blue = 8bc0ff
$lavender = aecfff
$klink = 468cca
$klinkSelection = 468cca
$kvisited = 4a7fdb
$kvisitedSelection = 4a7fdb
$knegative = 607eff
$knegativeSelection = 617dff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b6ef
$kpositiveSelection = 00b6f0
$text = f5ddda
$subtext1 = dfbfba
$subtext0 = a78a86
$overlay2 = 927874
$overlay1 = 7d6562
$overlay0 = 695551
$surface2 = 574441
$surface1 = 443431
$surface0 = 302220
$base = 1c110f
$mantle = 1c110f
$crust = 1b100e
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
