$primary_paletteKeyColor = ad6257
$secondary_paletteKeyColor = 926f69
$tertiary_paletteKeyColor = 8a7444
$neutral_paletteKeyColor = 827472
$neutral_variant_paletteKeyColor = 857370
$background = 1a1110
$onBackground = f1dedc
$surface = 1a1110
$surfaceDim = 1a1110
$surfaceBright = 423735
$surfaceContainerLowest = 140c0b
$surfaceContainerLow = 231918
$surfaceContainer = 271d1c
$surfaceContainerHigh = 322826
$surfaceContainerHighest = 3d3231
$onSurface = f1dedc
$surfaceVariant = 534341
$onSurfaceVariant = d8c2be
$inverseSurface = f1dedc
$inverseOnSurface = 392e2c
$outline = a08c89
$outlineVariant = 534341
$shadow = 000000
$scrim = 000000
$surfaceTint = ffb4a8
$primary = ffb4a8
$onPrimary = 561e17
$primaryContainer = 73342b
$onPrimaryContainer = ffdad5
$inversePrimary = 904a40
$secondary = e7bdb6
$onSecondary = 442925
$secondaryContainer = 5d3f3b
$onSecondaryContainer = ffdad5
$tertiary = dec38c
$onTertiary = 3e2e04
$tertiaryContainer = a58e5b
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffdad5
$primaryFixedDim = ffb4a8
$onPrimaryFixed = 3b0905
$onPrimaryFixedVariant = 73342b
$secondaryFixed = ffdad5
$secondaryFixedDim = e7bdb6
$onSecondaryFixed = 2c1512
$onSecondaryFixedVariant = 5d3f3b
$tertiaryFixed = fcdfa6
$tertiaryFixedDim = dec38c
$onTertiaryFixed = 251a00
$onTertiaryFixedVariant = 564419
$term0 = 353434
$term1 = ff5543
$term2 = ffbd9f
$term3 = ffdfd5
$term4 = b9ab66
$term5 = f18f8c
$term6 = ffba8f
$term7 = efd2c9
$term8 = b49e98
$term9 = ff8674
$term10 = ffd4c2
$term11 = fff1ed
$term12 = dcbc93
$term13 = ffa8a2
$term14 = ffd2b9
$term15 = ffffff
$rosewater = ffeeeb
$flamingo = ffd9d5
$pink = ffd2d2
$mauve = ffa8b3
$red = ff9791
$maroon = faaaa3
$peach = ffbeaf
$yellow = ffeee8
$green = ffd8c2
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = ffa2bd
$lavender = ffbac8
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = ce5c68
$kvisitedSelection = ce5c69
$knegative = eb5447
$knegativeSelection = eb5448
$kneutral = ff896e
$kneutralSelection = ff896e
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f1dedc
$subtext1 = d8c2be
$subtext0 = a08c89
$overlay2 = 8c7a77
$overlay1 = 786764
$overlay0 = 655653
$surface2 = 534543
$surface1 = 413433
$surface0 = 2d2221
$base = 1a1110
$mantle = 1a1110
$crust = 19100f
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
