$background = 081104
$onBackground = d6edc4
$surface = 081104
$surfaceDim = 081104
$surfaceBright = 1d3113
$surfaceContainerLowest = 000000
$surfaceContainerLow = 0b1606
$surfaceContainer = 101d09
$surfaceContainerHigh = 14230c
$surfaceContainerHighest = 192a10
$onSurface = d6edc4
$surfaceVariant = 192a10
$onSurfaceVariant = 9cb28c
$outline = 677b59
$outlineVariant = 3a4d2f
$inverseSurface = f1fee4
$inverseOnSurface = 4d5845
$shadow = 000000
$scrim = 000000
$surfaceTint = f1ffd2
$primary = f1ffd2
$primaryDim = daf5a7
$onPrimary = 506628
$primaryContainer = daf5a7
$onPrimaryContainer = 485e21
$inversePrimary = 506628
$primaryFixed = d1ec9f
$primaryFixedDim = c4de93
$onPrimaryFixed = 31450a
$onPrimaryFixedVariant = 4d6325
$secondary = c5c4dd
$secondaryDim = b7b7cf
$onSecondary = 3e3f52
$secondaryContainer = 232437
$onSecondaryContainer = a2a2b9
$secondaryFixed = e1e0f9
$secondaryFixedDim = d3d2eb
$onSecondaryFixed = 3d3e51
$onSecondaryFixedVariant = 595a6f
$tertiary = c4c0ff
$tertiaryDim = a9a4ff
$onTertiary = 3a3487
$tertiaryContainer = b5b1ff
$onTertiaryContainer = 302a7d
$tertiaryFixed = b5b1ff
$tertiaryFixedDim = a6a1fc
$onTertiaryFixed = 180d67
$onTertiaryFixedVariant = 393487
$error = fe7453
$errorDim = c74c2f
$onError = 450900
$errorContainer = 881f05
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = 687f3e
$secondaryPaletteKeyColor = 75758b
$tertiaryPaletteKeyColor = 716dc3
$neutralPaletteKeyColor = 6f7b66
$neutralVariantPaletteKeyColor = 60804e
$errorPaletteKeyColor = cb4f31
$primary_paletteKeyColor = 687f3e
$secondary_paletteKeyColor = 75758b
$tertiary_paletteKeyColor = 716dc3
$neutral_paletteKeyColor = 6f7b66
$neutral_variant_paletteKeyColor = 60804e
$term0 = 343433
$term1 = 9b9400
$term2 = b9d867
$term3 = dfef76
$term4 = 90b484
$term5 = c6a844
$term6 = b3d48b
$term7 = d9dac3
$term8 = a4a492
$term9 = b4ad00
$term10 = c6eb66
$term11 = eaff79
$term12 = b4c7a4
$term13 = cec06b
$term14 = c4e793
$term15 = ffffff
$rosewater = f6f2e1
$flamingo = e8e2c2
$pink = ffd79d
$mauve = 5bd0df
$red = c5b542
$maroon = cbc075
$peach = d1d288
$yellow = eff5c6
$green = c7ec98
$teal = c2ebac
$sky = b5e8ab
$sapphire = 98d698
$blue = 75cf9d
$lavender = 89dcc6
$klink = 49975b
$klinkSelection = 4a975b
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = 948a00
$knegativeSelection = 948a00
$kneutral = adb100
$kneutralSelection = aeb100
$kpositive = 7eb943
$kpositiveSelection = 7eb943
$text = d6edc4
$subtext1 = 9cb28c
$subtext0 = 677b59
$overlay2 = 5a6c4d
$overlay1 = 4b5c40
$overlay0 = 3e4d34
$surface2 = 323f28
$surface1 = 25311d
$surface0 = 162110
$base = 081104
$mantle = 081104
$crust = 081004
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
