decoration {
    rounding = $windowRounding
    # screen_shader = ~/.config/hypr/shaders/32-bit.glsl

    blur {
        enabled = $blurEnabled
        xray = $blurXray
        special = $blurSpecialWs
        ignore_opacity = true  # Allows opacity blurring
        new_optimizations = true
        popups = $blurPopups
        input_methods = $blurInputMethods
        size = $blurSize
        passes = $blurPasses
    }

    shadow {
        enabled = $shadowEnabled
        range = $shadowRange
        render_power = $shadowRenderPower
        color = $shadowColour
    }
}
